# Generated by Django 5.0.3 on 2025-07-04 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steelsheet',
            old_name='name',
            new_name='part_name',
        ),
        migrations.RemoveField(
            model_name='steelsheet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='steelsheet',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='steelsheet',
            name='price',
        ),
        migrations.AddField(
            model_name='steelsheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steelsheet',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='steelsheet',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='steelsheet',
            name='lot_number',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steelsheet',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='steelsheet',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='steelsheet',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='steelsheet',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
