# Generated by Django 5.0.3 on 2025-07-05 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_name_steelsheet_part_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SteelSheetInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(auto_now_add=True)),
                ('surface_deformation', models.BooleanField(default=False, help_text='Surface deformation detected?')),
                ('scratches_percent', models.PositiveSmallIntegerField(default=0, help_text='Percent of scratches on surface')),
                ('dent', models.BooleanField(default=False)),
                ('stain', models.BooleanField(default=False)),
                ('other_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('conductivity_test', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], default='pass', max_length=8)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('disapprove', 'Disapprove')], default='approve', max_length=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='pages.steelsheet')),
            ],
        ),
    ]
