# Generated by Django 5.0.3 on 2025-07-06 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_steelsheetinspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('machine_id', models.CharField(max_length=100)),
                ('date_scanned', models.DateField()),
                ('time_scanned', models.TimeField()),
                ('condition', models.CharField(max_length=100)),
                ('num_defects', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scan_images/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanlogs', to=settings.AUTH_USER_MODEL)),
                ('qc_manager_tagged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_tagged_scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
