# Generated by Django 5.1.3 on 2024-12-05 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_task_created_at_remove_task_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="title",
            new_name="task_name",
        ),
    ]
